"""
YuE Studio — Song Stitcher
Joins per-section WAVs (intro/verse/chorus/outro) into one song file
with optional crossfade.  Also turns a "song plan" (sequence of named
sections with bar counts) into a list of YuE inference calls that fit
inside the 8GB VRAM 30s-per-segment cap.

Designed for 8GB VRAM: each section is generated by one or more YuE
calls, where every call is hard-capped at MAX_BARS_PER_SEGMENT bars
(~12 bars ≈ 30s).  The resulting WAVs are then concatenated with
pydub crossfade to produce the final song of any length.

Usage:
    from song_stitcher import (
        SongSection, SongPlan, expand_plan_to_calls,
        split_lyrics_into_sections, make_section_genre_tags,
        stitch_sections, build_song,
        POP_STRUCTURE,  # canonical intro(1) verse(8) chorus(4) verse2(8) chorus2(4) outro(1)
    )

Requires: pydub + ffmpeg on PATH.
"""

from __future__ import annotations

import math
import re
import wave
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Optional, Union

try:
    from pydub import AudioSegment
except ImportError:  # pragma: no cover
    AudioSegment = None  # type: ignore[assignment]


# ─── 8GB VRAM caps ──────────────────────────────────────────────────────────
# Mirrors the constants in yue_studio.MAX_SEGMENTS / MAX_DURATION_SECONDS.
# Hard-coded here so this module is self-contained (no circular import).
MAX_DURATION_SECONDS = 30
SECONDS_PER_BAR      = 2.4   # 4/4 @ 100 BPM
MAX_BARS_PER_SEGMENT = int(MAX_DURATION_SECONDS / SECONDS_PER_BAR)  # 12

# When stitching per-section WAVs, the leading/trailing silence of each
# 30s render is real silence, so we trim it before the crossfade to
# avoid stacking 4 seconds of dead air around each transition.
TRIM_HEAD_MS_DEFAULT = 1500
TRIM_TAIL_MS_DEFAULT = 1500


# ─── Section types ──────────────────────────────────────────────────────────
SUPPORTED_SECTIONS = ["intro", "verse", "chorus", "bridge", "outro", "hook"]


@dataclass
class SongSection:
    """One named section of a song (e.g. a verse or chorus)."""
    name: str                                  # "intro", "verse", "chorus", ...
    lyrics: str                                # raw lyrics for this section
    genre_tags: str = ""                       # base genre tags (without role-tags)
    bars: int = 8                              # target bar count
    suffix: str = ""                           # optional: " 2" to distinguish repeats


@dataclass
class InferenceCall:
    """One YuE inference job (≤30s, ≤12 bars).  This is what actually
    gets run by `build_infer_command` + `run_generation`."""
    call_id: str                               # e.g. "verse2_chunk1"
    section_name: str                          # e.g. "verse"
    lyrics: str                                # lyrics for this call only
    genre_tags: str                            # tags (role + section + base)
    bars: int                                  # 1..MAX_BARS_PER_SEGMENT


@dataclass
class SongPlan:
    """High-level description of a song structure."""
    name: str                                  # "pop", "custom", ...
    sections: list[SongSection] = field(default_factory=list)


# ─── Canonical pop structure ───────────────────────────────────────────────
# Intro (1 bar) → Verse 1 (8 bars) → Chorus 1 (4 bars)
#          → Verse 2 (8 bars) → Chorus 2 (4 bars) → Outro (1 bar)
POP_STRUCTURE: list[dict] = [
    {"name": "intro",  "bars": 1, "suffix": ""},
    {"name": "verse",  "bars": 8, "suffix": ""},
    {"name": "chorus", "bars": 4, "suffix": ""},
    {"name": "verse",  "bars": 8, "suffix": " 2"},
    {"name": "chorus", "bars": 4, "suffix": " 2"},
    {"name": "outro",  "bars": 1, "suffix": ""},
]

# A few more presets the UI / CLI can pick from.
STRUCTURE_PRESETS: dict[str, list[dict]] = {
    "pop": POP_STRUCTURE,
    "short": [
        {"name": "intro",  "bars": 1, "suffix": ""},
        {"name": "verse",  "bars": 4, "suffix": ""},
        {"name": "chorus", "bars": 4, "suffix": ""},
        {"name": "outro",  "bars": 1, "suffix": ""},
    ],
    "extended": [
        {"name": "intro",  "bars": 4, "suffix": ""},
        {"name": "verse",  "bars": 8, "suffix": ""},
        {"name": "chorus", "bars": 4, "suffix": ""},
        {"name": "verse",  "bars": 8, "suffix": " 2"},
        {"name": "chorus", "bars": 4, "suffix": " 2"},
        {"name": "bridge", "bars": 4, "suffix": ""},
        {"name": "chorus", "bars": 4, "suffix": " 3"},
        {"name": "outro",  "bars": 4, "suffix": ""},
    ],
}


# ─── Lyrics splitting ──────────────────────────────────────────────────────
_SECTION_RE = re.compile(
    r"^\s*\[(?P<name>" + "|".join(SUPPORTED_SECTIONS) + r")\]\s*$",
    re.IGNORECASE | re.MULTILINE,
)


def split_lyrics_into_sections(lyrics: str) -> list[SongSection]:
    """
    Parse lyrics with `[verse]`, `[chorus]`, `[intro]`, `[outro]`,
    `[bridge]`, `[hook]` markers into a list of SongSection.

    If no section markers are present the whole text is returned as a
    single `[verse]` section (with default 8 bars).
    """
    text = (lyrics or "").strip()
    if not text:
        return []

    matches = list(_SECTION_RE.finditer(text))
    if not matches:
        return [SongSection(name="verse", lyrics=text, bars=8)]

    sections: list[SongSection] = []
    for i, m in enumerate(matches):
        name = m.group("name").lower()
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = text[start:end].strip()
        if not body:
            continue
        # Auto-count bars: 1 bar ≈ 1 line of lyrics (rough).
        line_count = max(1, len([l for l in body.splitlines() if l.strip()]))
        sections.append(SongSection(
            name=name, lyrics=body,
            bars=max(2, min(line_count, 24)),  # clamp to a sane range
        ))
    return sections


def _pad_lyrics(lyrics: str, target_lines: int) -> str:
    """
    If a section's lyrics have fewer lines than `target_lines`, repeat
    the last non-empty line (or pad with a hum) until we hit the count.
    This keeps YuE from generating dead-air when we ask for 8 bars but
    only wrote 2 lines of verse.
    """
    lines = [l for l in (lyrics or "").splitlines() if l.strip()]
    if not lines:
        return "Mmm, mm\nMmm, mm\nMmm, mm"
    filler = lines[-1]
    while len(lines) < target_lines:
        lines.append(filler)
    return "\n".join(lines)


def _split_lyrics_for_call(
    full_lyrics: str, chunk_index: int, chunk_count: int,
) -> str:
    """
    When a section is split across multiple inference calls (e.g. an
    8-bar verse becomes 2×4-bar calls), split the lyrics evenly across
    the calls.  Returns the lyrics assigned to chunk `chunk_index`
    (0-based) of `chunk_count` total.
    """
    lines = [l for l in (full_lyrics or "").splitlines() if l.strip()]
    if not lines or chunk_count <= 1:
        return full_lyrics
    # Round up so the last chunk is no bigger than the others
    size = max(1, math.ceil(len(lines) / chunk_count))
    start = chunk_index * size
    end = start + size
    chunk = lines[start:end]
    if not chunk:
        chunk = lines[-1:]  # safety: at least one line
    return "\n".join(chunk)


# ─── Plan → calls (the core of the multi-section generator) ────────────────
def expand_plan_to_calls(
    plan: SongPlan,
    base_genre_tags: str,
) -> list[InferenceCall]:
    """
    Take a SongPlan and return the list of InferenceCall objects needed
    to render the whole song on 8GB VRAM.

    Each section with `bars > MAX_BARS_PER_SEGMENT` is split into
    multiple consecutive calls (chunk1, chunk2, ...) with the lyrics
    split evenly between them.
    """
    calls: list[InferenceCall] = []
    for sidx, section in enumerate(plan.sections):
        target = max(1, int(section.bars))
        chunk_count = max(1, math.ceil(target / MAX_BARS_PER_SEGMENT))
        # Even split — last chunk may be slightly smaller
        per_chunk = max(1, math.ceil(target / chunk_count))

        # The first chunk is where the section "starts" (gets the role tag)
        # Subsequent chunks are continuations and get a "continuation" tag.
        is_first_section = sidx == 0
        for cidx in range(chunk_count):
            call_id = f"{section.name}{section.suffix.replace(' ', '_')}_chunk{cidx+1}"
            tag_suffix = "" if (cidx == 0) else " continuation"
            section_tag = f"[{section.name}{section.suffix}]{tag_suffix}"
            tags = make_section_genre_tags(
                base_genre_tags,
                # We pretend the chunk *is* the full section for tag purposes
                # so role tags ("verse", "chorus", ...) are always applied.
                SongSection(
                    name=section.name, lyrics=section.lyrics, bars=per_chunk,
                ),
            )
            if cidx > 0:
                # Continuation chunks — make sure the tag order survives
                tags = f"continuation {tags}"
            lyrics = _split_lyrics_for_call(section.lyrics, cidx, chunk_count)
            # Pad short lyrics to the bar count
            lyrics = _pad_lyrics(lyrics, per_chunk)
            calls.append(InferenceCall(
                call_id=call_id,
                section_name=f"{section.name}{section.suffix}",
                lyrics=f"{section_tag}\n{lyrics}".strip(),
                genre_tags=tags,
                bars=per_chunk,
            ))
    return calls


# ─── Per-section genre tag augmentation ─────────────────────────────────────
SECTION_TAGS = {
    "intro":  ["intro",  "fade-in",   "soft", "instrumental-build"],
    "verse":  ["verse",  "narrative", "moderate-energy"],
    "chorus": ["chorus", "hook",      "energetic", "bright-vocal"],
    "bridge": ["bridge", "contrast",  "build-up"],
    "outro":  ["outro",  "fade-out",  "soft", "instrumental-tail"],
    "hook":   ["hook",   "catchy",    "repetitive"],
}


def make_section_genre_tags(base_tags: str, section: SongSection) -> str:
    """
    Combine the user's genre tags with section-specific role tags so
    YuE knows the role of each section.  Duplicates removed, order kept.
    """
    out: list[str] = []
    seen: set[str] = set()
    for src in (base_tags, section.genre_tags, *SECTION_TAGS.get(section.name, [])):
        for tag in src.split():
            tag = tag.strip()
            if tag and tag not in seen:
                seen.add(tag)
                out.append(tag)
    return " ".join(out)


# ─── Plan summary helpers (for UI) ─────────────────────────────────────────
def describe_plan(plan) -> str:
    """Human-readable plan summary, e.g. 'intro(1) → verse(8) → ...'.

    Accepts a SongPlan OR a list of section dicts (so callers can pass
    POP_STRUCTURE / STRUCTURE_PRESETS[...] directly).
    """
    if isinstance(plan, SongPlan):
        items = plan.sections
    else:
        # list of {"name": ..., "bars": ..., "suffix": ...} dicts
        items = plan
    def _name(item):
        return item["name"] if isinstance(item, dict) else item.name
    def _bars(item):
        return item["bars"] if isinstance(item, dict) else item.bars
    def _suffix(item):
        if isinstance(item, dict):
            return item.get("suffix", "") or ""
        return getattr(item, "suffix", "") or ""

    parts = [f"{_name(s)}{_suffix(s)}({_bars(s)})" for s in items]
    return " → ".join(parts) if parts else "(empty plan)"


def plan_total_bars(plan: SongPlan) -> int:
    return sum(max(1, s.bars) for s in plan.sections)


def plan_total_calls(plan: SongPlan) -> int:
    return sum(
        max(1, math.ceil(max(1, s.bars) / MAX_BARS_PER_SEGMENT))
        for s in plan.sections
    )


# ─── Auto-build a plan from lyrics + preset name ───────────────────────────
def build_plan_from_lyrics(
    lyrics: str,
    preset: str = "pop",
    add_intro: bool = True,
    add_outro: bool = True,
) -> SongPlan:
    """
    Build a SongPlan from lyrics and a structure preset.

    The lyrics' explicit section markers (`[verse]`, `[chorus]`, ...)
    are honoured when present — the preset's bar counts override the
    auto-detected bar count from line counting.  If a section type is
    present in the preset but missing from the lyrics, a placeholder
    section is added.  If the user disabled add_intro/add_outro, those
    are stripped.
    """
    preset_sections = STRUCTURE_PRESETS.get(preset, STRUCTURE_PRESETS["pop"])
    parsed = split_lyrics_into_sections(lyrics)
    parsed_by_name: dict[str, list[SongSection]] = {}
    for s in parsed:
        parsed_by_name.setdefault(s.name, []).append(s)

    plan_sections: list[SongSection] = []
    section_occurrences: dict[str, int] = {}
    for psec in preset_sections:
        name = psec["name"]
        idx = section_occurrences.get(name, 0)
        section_occurrences[name] = idx + 1
        # Find a lyrics slot for this occurrence (if any)
        lyrics_text = ""
        if name in parsed_by_name and idx < len(parsed_by_name[name]):
            lyrics_text = parsed_by_name[name][idx].lyrics
        # If this section is the intro/outro and the user said no, skip
        if name == "intro" and not add_intro:
            continue
        if name == "outro" and not add_outro:
            continue
        # If no lyrics at all, auto-pad with hum/fade hints
        if not lyrics_text:
            if name == "intro":
                lyrics_text = "Mmm, mm\nLet it build\nMmm, mm"
            elif name == "outro":
                lyrics_text = "Mmm, mm\nLet it fade\nMmm, mm"
            else:
                lyrics_text = "Mmm, mm\nMmm, mm\nMmm, mm"
        plan_sections.append(SongSection(
            name=name,
            lyrics=lyrics_text,
            bars=int(psec["bars"]),
            suffix=psec.get("suffix", ""),
        ))
    return SongPlan(name=preset, sections=plan_sections)


# ─── WAV stitching ──────────────────────────────────────────────────────────
def _read_wav_duration_s(path: Path) -> float:
    """Cheap duration lookup that doesn't need ffmpeg/pydub."""
    try:
        with wave.open(str(path), "rb") as wf:
            frames = wf.getnframes()
            rate   = wf.getframerate()
            return frames / float(rate) if rate else 0.0
    except Exception:
        return 0.0


def _trim_silence(
    seg: "AudioSegment",
    head_ms: int = TRIM_HEAD_MS_DEFAULT,
    tail_ms: int = TRIM_TAIL_MS_DEFAULT,
) -> "AudioSegment":
    """Trim up to N ms off the head and tail of a section to avoid
    stacking dead-air from the leading/trailing silence of a 30s render."""
    if AudioSegment is None:
        return seg
    if head_ms and len(seg) > head_ms:
        seg = seg[head_ms:]
    if tail_ms and len(seg) > tail_ms:
        seg = seg[:-tail_ms]
    return seg


def stitch_sections(
    wavs: list[Path],
    out_path: Path,
    crossfade_ms: int = 1500,
    silence_ms: int = 0,
    trim_head_ms: int = TRIM_HEAD_MS_DEFAULT,
    trim_tail_ms: int = TRIM_TAIL_MS_DEFAULT,
) -> Path:
    """
    Concatenate per-section WAVs with `crossfade_ms` crossfades between
    them and an optional `silence_ms` gap before each new section.

    Trims the first `trim_head_ms` from the head of section #1 and the
    last `trim_tail_ms` from the tail of the final section (YuE renders
    always include ~1–4s of dead silence at the edges that would
    otherwise accumulate).

    Falls back to a raw-bytes copy of the first wav if pydub isn't
    available.
    """
    if not wavs:
        raise ValueError("stitch_sections: no input wavs supplied")
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if AudioSegment is None:
        # Fallback: just copy the first wav.  Not ideal, but the user
        # can install pydub and re-run.
        out_path.write_bytes(Path(wavs[0]).read_bytes())
        return out_path

    segments = [_trim_silence(AudioSegment.from_wav(str(w)),
                               head_ms=trim_head_ms,
                               tail_ms=trim_tail_ms) for w in wavs]
    out = segments[0]
    for nxt in segments[1:]:
        if crossfade_ms > 0 and len(out) > crossfade_ms and len(nxt) > crossfade_ms:
            out = out.append(nxt, crossfade=crossfade_ms)
        else:
            if silence_ms > 0:
                out = out + AudioSegment.silent(duration=silence_ms)
            out = out + nxt
    out.export(str(out_path), format="wav")
    return out_path


def build_song(
    section_wavs: dict[str, Path],
    out_path: Path,
    order: Optional[list[str]] = None,
    crossfade_ms: int = 1500,
) -> Path:
    """
    Convenience wrapper: takes a {section_name: wav_path} dict and builds
    a song in the given section order (default: intro/verse/chorus/.../outro).
    Section names with a suffix (e.g. "verse 2") are matched by their
    full name first, then by base name.
    """
    if order is None:
        order = ["intro", "verse", "chorus", "verse 2", "chorus 2",
                 "bridge", "verse 3", "chorus 3", "outro"]
        order = [s for s in order if s in section_wavs]
        # add any remaining sections at the end
        order += [s for s in section_wavs if s not in order]
    wavs = [section_wavs[s] for s in order if s in section_wavs]
    return stitch_sections(wavs, out_path, crossfade_ms=crossfade_ms)


# ─── Convenience: find generated wavs in a per-section output dir ──────────
def find_section_wav(section_dir: Path) -> Optional[Path]:
    """Look in a per-section output directory for the first .wav file."""
    if not section_dir or not Path(section_dir).exists():
        return None
    wavs = sorted(Path(section_dir).rglob("*.wav"))
    return wavs[0] if wavs else None
